### ISSUE TITLE
Portfolio section

### ISSUE THREAD

**Issue by cesargomezh** [cesargomezh/me#1]
I'm still deciding how to use Portfolio section. I have idea about place here products where I have worked before, but need add info about them, maybe modals or accordions, I'm not sure.

I'm struggling now how implement this with ngx-translate support, so I'm going to keep opened this issue.

**Comment by cesargomezh** [comment]
My friend gave me a good idea: using Slider. It is responsive and nice to mobiles.

**Comment by mrcego** [comment]
I'm finally decided for grid cards ([commit referenced](https://github.com/mrcego/me-angular/commit/9678ef257ca7ea3776dda3cb7a5bbdcd9b2d4a45))
